os: linux
dist: xenial
language: node_js
node_js:
- 9.5.0

branches:
  except:
    - /^latest$/

addons:
  apt:
    packages:
      - rpm

env:
  global:
    - PACKAGE_BUILD_IMAGE=sorintdev/rpmbuild-centos7
    - WORKSPACE='/project'


before_install:
  - if [ -z ${TRAVIS_TAG} ] || [ ${TRAVIS_TAG} == *-* ]; then export VERSION=latest; else export VERSION=${TRAVIS_TAG}; fi
  - echo ${TRAVIS_TAG}
  - echo ${VERSION}
  # - sudo docker pull ${PACKAGE_BUILD_IMAGE}

install:
  # - sudo docker run -d --rm -it -e WORKSPACE="${WORKSPACE}" -e TRAVIS_REPO_SLUG="${TRAVIS_REPO_SLUG}" -e TRAVIS_BUILD_NUMBER="${TRAVIS_BUILD_NUMBER}" -v $PWD:"${WORKSPACE}" --name package_builder ${PACKAGE_BUILD_IMAGE} /bin/cat
  - mkdir /tmp/dist
  - gem install --no-document fpm
  - npm install

script:
  - if [[ ${VERSION} == "latest" ]]; then sed -r 's/(ercole-agent((-virtualization)|(-setup))?)-(.*)((-1(.el[567])?.x86_64.rpm)|.exe)/\1-latest\6/' src/views/Agent.vue > /tmp/Agent.vue; fi
  - if [[ ${VERSION} == "latest" ]]; then cp /tmp/Agent.vue src/views/Agent.vue; fi
  - if [[ ${VERSION} == "latest" ]]; then sed -r 's/(Ercole )(.*)( &copy; 2018-19 Sorint.lab S.p.A.)/\1latest\3/' src/App.vue src/App.vue > /tmp/App.vue; fi
  - if [[ ${VERSION} == "latest" ]]; then cp /tmp/App.vue src/views/App.vue; fi
  - npm run build
  - tar -C dist -czf /tmp/dist/ercole-web-${VERSION}.tar.gz .
  - fpm -n ercole-web -s dir -t rpm -a all --rpm-os rhel7 --version ${VERSION} --name ercole-web -s dir dist=/usr/share/ercole/web
  - mv ercole-web-${VERSION}-1.noarch.rpm /tmp/dist
  # - docker exec -it package_builder /bin/sh -c "mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}"
  # - docker exec -it package_builder /bin/sh -c "ln -s ${WORKSPACE} ~/rpmbuild/SOURCES/ercole-web-${VERSION}"
  # - docker exec -it package_builder /bin/sh -c "cd ${WORKSPACE} && rpmbuild --define \"_version ${VERSION}\" -bb package/rhel7/ercole-web.spec"
  # - docker exec -it package_builder /bin/sh -c "ls ~/rpmbuild/RPMS/x86_64/ercole-web-*.rpm"
  # - docker exec -it package_builder /bin/sh -c "file ~/rpmbuild/RPMS/x86_64/ercole-web-*.rpm"
  # - docker exec -it package_builder /bin/sh -c "cp ~/rpmbuild/RPMS/x86_64/ercole-web-*.rpm ${WORKSPACE}/dist"

before_deploy:
  - if [[ ${VERSION} == "latest" ]]; then git tag -f latest; fi
  - if [[ ${VERSION} == "latest" ]]; then git remote add gh https://simonerota:${GITHUB_RELEASE_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git; fi
  - if [[ ${VERSION} == "latest" ]]; then git push gh latest || true; fi
  - if [[ ${VERSION} == "latest" ]]; then git push -f gh latest; fi
  - if [[ ${VERSION} == "latest" ]]; then git remote remove gh; fi

deploy:
  provider: releases
  api_key: $GITHUB_RELEASE_TOKEN
  file_glob: true
  file: /tmp/dist/*
  skip_cleanup: true
  name: $VERSION
  overwrite: true
  on:
    all_branches: true
